USE [master]
GO

/****** Object:  Database [pilot]    Script Date: 20/02/2023 11:55:12 ******/
CREATE DATABASE [pilot]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'pilot', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\pilot.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'pilot_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\pilot_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [pilot].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [pilot] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [pilot] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [pilot] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [pilot] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [pilot] SET ARITHABORT OFF 
GO

ALTER DATABASE [pilot] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [pilot] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [pilot] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [pilot] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [pilot] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [pilot] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [pilot] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [pilot] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [pilot] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [pilot] SET  ENABLE_BROKER 
GO

ALTER DATABASE [pilot] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [pilot] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [pilot] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [pilot] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [pilot] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [pilot] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [pilot] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [pilot] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [pilot] SET  MULTI_USER 
GO

ALTER DATABASE [pilot] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [pilot] SET DB_CHAINING OFF 
GO

ALTER DATABASE [pilot] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [pilot] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [pilot] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [pilot] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [pilot] SET QUERY_STORE = OFF
GO

ALTER DATABASE [pilot] SET  READ_WRITE 
GO

